---

- name: Create {{ poudriere_ssl_dir }}
  file: >
    path="{{ poudriere_ssl_dir }}"
    state="directory"
    owner="{{ poudriere_owner }}"
    group="{{ poudriere_group }}"
  tags: poudriere_ssl_dirs

- name: Create {{ poudriere_ssl_dir }}/crt
  file: >
    path="{{ poudriere_ssl_dir }}/crt"
    state="directory"
    owner="{{ poudriere_owner }}"
    group="{{ poudriere_group }}"
  tags: poudriere_ssl_dirs

- name: Create {{ poudriere_ssl_dir }}/csr
  file: >
    path="{{ poudriere_ssl_dir }}/csr"
    state="directory"
    owner="{{ poudriere_owner }}"
    group="{{ poudriere_group }}"
  tags: poudriere_ssl_dirs

- name: Create {{ poudriere_ssl_dir }}/private
  file: >
    path="{{ poudriere_ssl_dir }}/private"
    state="directory"
    owner="{{ poudriere_owner }}"
    group="{{ poudriere_group }}"
    mode="0700"
  tags: poudriere_ssl_dirs

- name: Generate an OpenSSL private key (default 4096 bits, RSA)
  openssl_privatekey: >
    path="{{ poudriere_conf_PKG_REPO_SIGNING_KEY }}"
  tags: poudriere_crt

- name: Generate an OpenSSL Certificate Signing Request
  openssl_csr: >
    path="{{ poudriere_ssl_dir }}/csr/poudriere.csr"
    privatekey_path="{{ poudriere_conf_PKG_REPO_SIGNING_KEY }}"
    common_name="{{ poudriere_cert_CN }}"
  tags: poudriere_crt

- name: Generate a Self Signed OpenSSL certificate
  openssl_certificate: >
    path="{{ poudriere_cert_path }}"
    privatekey_path="{{ poudriere_conf_PKG_REPO_SIGNING_KEY }}"
    csr_path="{{ poudriere_ssl_dir }}/csr/poudriere.csr"
    provider="selfsigned"
  tags: poudriere_crt

# EOF
...
