---

- name: "conf: Create directories"
  file:
    state: directory
    path: "{{ item.dir }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ poudriere_conf_dirs }}"
  tags: poudriere_conf_dirs

- name: "conf: Configure {{ poudriere_conf_file }}"
  template:
    src: "poudriere.conf.j2"
    dest: "{{ poudriere_conf_file }}"
    owner: "{{ poudriere_owner }}"
    group: "{{ poudriere_group }}"
    mode: "{{ poudriere_mode }}"
    backup: "{{ poudriere_backup_conf|bool }}"
  tags: poudriere_conf_file

# EOF
...
