---
# tasks freebsd-poudriere

- import_tasks: debug.yml
  when: poudriere_debug
  tags: poudriere_debug

- import_tasks: packages.yml
  tags: poudriere_packages

- import_tasks: cert.yml
  tags: poudriere_cert

- import_tasks: conf.yml
  tags: poudriere_conf

- import_tasks: make.yml
  tags: poudriere_make

# EOF
...
