---

- name: "packages: Install poudriere packages"
  pkgng:
    name: "{{ poudriere_packages }}"
  register: result
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"
  when: freebsd_install_method == "packages"

- name: "packages: Install poudriere ports"
  portinstall:
    name: "{{ item }}"
    use_packages: "{{ freebsd_use_packages }}"
  loop: "{{ poudriere_packages }}"
  register: result
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"
  when: freebsd_install_method == "ports"

- name: "packages: Install packages to create certificate"
  pkgng:
    name: "{{ poudriere_packages_cert }}"
  register: result
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"
  when:
    - poudriere_cert_create|bool
    - freebsd_install_method == "packages"

- name: "packages: Install ports to create certificate"
  portinstall:
    name: "{{ item }}"
    use_packages: "{{ freebsd_use_packages }}"
  loop: "{{ poudriere_packages_cert }}"
  register: result
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"
  when:
    - poudriere_cert_create|bool
    - freebsd_install_method == "ports"

# EOF
...
